---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: "semver:~0."
    filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "false"
  name: home-assistant
  namespace: default
spec:
  chart:
    name: home-assistant
    repository: "https://k8s-at-home.com/charts/"
    version: 5.1.1
  releaseName: home-assistant
  rollback:
    enable: true
  values:
    env:
      TZ: "Europe/London"
    hostNetwork: true
    image:
      repository: homeassistant/home-assistant
      tag: 2021.1.4
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      hosts:
      - host: hass.starbs.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - hass.starbs.net
    monitoring:
      enabled: false
    persistence:
      enabled: true
      size: 2Gi
      storageClass: local-path
    postgresql:
      enabled: true
      #image:
      #  repository: arm64v8/postgres
      #  tag: 13.0-alpine
      persistence:
        enabled: true
        storageClass: local-path
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 100m
        memory: 1000Mi
    service:
      loadBalancerIP: 172.16.1.114
      type: LoadBalancer
    tolerations:
    - key: "arm"
      operator: "Exists"
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.8.0
        workingDir: "/config"
        args:
        - --user-data-dir
        - "/config/.vscode"
        - --auth
        - "none"
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
        enabled: true
        hosts:
        - host: hass-vscode.starbs.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - hass-vscode.starbs.net
      volumeMounts:
      - name: config
        mountPath: /config
