---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.
    filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 2.5.0
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.117.1
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "local-path"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - hass.starbs.net
      tls:
      - hosts:
        - hass.starbs.net
    service:
      type: LoadBalancer
      loadBalancerIP: 172.16.1.114
    hostNetwork: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.5.0
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - hass-vscode.starbs.net
        tls:
        - hosts:
          - hass-vscode.starbs.net
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 512Mi
    monitoring:
      enabled: false
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: "local-path"
