---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.2.3
    env:
      TZ: "Europe/London"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      type: LoadBalancer
      loadBalancerIP: 172.16.1.116
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: hass.starbs.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "hass.starbs.net"
    #prometheus:
    #  serviceMonitor:
    #    enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        storageClass: "openebs-hostpath"
        accessMode: ReadWriteOnce
        skipuninstall: true
        size: "10Gi"
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.9.0
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - host: hass-vscode.starbs.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hass-vscode.starbs.net
        volumeMounts:
          - name: config
            mountPath: /config
    tolerations:
      - key: "arm"
        operator: "Exists"
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 100m
        memory: 1000Mi
    postgresql:
      enabled: true
      postgresqlUsername: home-assistant
      postgresqlDatabase: home-assistant
      persistence:
        enabled: true
        storageClass: "openebs-hostpath"
        skipuninstall: true
