---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    tolerations:
      - key: "arm"
        operator: "Exists"
    replicaCount: 2
    serviceType: LoadBalancer
    #prometheus:
    #  service:
    #    enabled: true
    #  monitor:
    #    enabled: true
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: 172.16.1.118
      annotations:
        metallb.universe.tf/allow-shared-ip: coredns
    rbac:
      create: true
    isClusterService: false
    servers:
      - zones:
          - zone: starbs.net.
            scheme: dns://
            use_tcp: false
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          # - name: kubernetes
          #   parameters: cluster.local in-addr.arpa ip6.arpa
          #   configBlock: |-
          #     pods insecure
          #     fallthrough in-addr.arpa ip6.arpa
          #     ttl 30
          #- name: prometheus
          #  parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
          - name: file
            parameters: /etc/coredns/starbs.net
    zoneFiles:
      - contents: |
          starbs.net.   IN SOA ns-235.awsdns-29.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
          *.starbs.net. IN A   172.16.1.119
          starbs.net. IN A   172.16.1.90
        domain: starbs.net
        filename: starbs.net
