---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  chart:
    name: helm-operator
    repository: "https://charts.fluxcd.io/"
    version: 1.2.0
  helmVersion: v3
  releaseName: helm-operator
  values:
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
        interval: 30s
        namespace: flux
        scrapeTimeout: 10s
  valuesFrom:
    - externalSourceRef:
        url: "https://raw.githubusercontent.com/chipwolf/k8s-gitops/master/flux/helm-operator/values.yaml"
