---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: kured
  chart:
    repository: https://weaveworks.github.io/kured
    name: kured
    version: 2.2.0
  valuesFrom:
    - secretKeyRef:
        name: kured-helm-values
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.5.0
    configuration:
      startTime: "6:00"
      endTime: "12:00"
    metrics:
      create: true
