{
 "title": "Home Assistant state changes",
 "description": "Home Assistant state changes using InfluxDB integration",
 "tags": [
  "hass",
  "influxdb",
  "iot"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain",
    "query": "SHOW TAG VALUES WITH KEY = \"domain\""
   },
   {
    "name": "measurement",
    "label": "Measurement",
    "query": "SHOW MEASUREMENTS WHERE \"domain\" =~ /^[[domain]]$/"
   },
   {
    "name": "entity_id",
    "label": "Entity ID",
    "query": "SHOW TAG VALUES FROM \"${measurement:raw}\" WITH KEY = \"entity_id\" WHERE domain = '$domain'"
   },
   {
    "name": "interval",
    "label": "Min time interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Minimum Values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id ($measurement)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"value\") FROM \"$measurement\" WHERE (\"entity_id\" =~ /^[[entity_id]]$/) AND $timeFilter GROUP BY time($__interval), \"entity_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id ($measurement)",
     "query": "SELECT mean(\"value\") FROM \"$measurement\" WHERE (\"entity_id\" =~ /^[[entity_id]]$/) AND $timeFilter GROUP BY time($__interval), \"entity_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Maximum Values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id ($measurement)",
     "query": "SELECT max(\"value\") FROM \"$measurement\" WHERE (\"entity_id\" =~ /^[[entity_id]]$/) AND $timeFilter GROUP BY time($__interval), \"entity_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Value Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"$measurement\" WHERE (\"entity_id\" =~ /^[[entity_id]]$/) AND $timeFilter GROUP BY time($__interval), \"entity_id\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}