---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: openebs-charts
        namespace: flux-system
      interval: 5m
  values:
    # required only for cStor & Jiva
    apiserver:
      enabled: true
    provisioner:
      enabled: false
    # openebs/openebs#3046
    webhook:
      failurePolicy: Ignore
