---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zwave2mqtt
  namespace: default
spec:
  releaseName: zwave2mqtt
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: zwave2mqtt
    version: 4.0.0
  values:
    image:
      repository: robertslando/zwave2mqtt
      tag: 3.4.0
    timezone: "America/New_York"
    device: "/dev/serial/by-id/usb-0658_0200-if00"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/custom-zwave", operator: In, values: ["true"]}
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "https://auth.starbs.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.starbs.net/oauth2/start
      hosts: [zwave2mqtt.starbs.net]
      tls:
      - hosts:
        - zwave2mqtt.starbs.net
    podAnnotations:
      backup.velero.io/backup-volumes: config
