---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "false"
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    name: rook-ceph
    repository: "https://charts.rook.io/release"
    version: v1.5.0
  releaseName: rook-ceph
  values:
    crds:
      enabled: false
    csi:
      attacher:
        image: "raspbernetes/csi-external-attacher:3.0.0"
      cephcsi:
        image: "quay.io/cephcsi/cephcsi:v3.1.2"
      kubeletDirPath: /var/lib/kubelet
      pluginTolerations:
        - key: arm
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
      provisionerTolerations:
        - key: arm
          operator: Exists
      provisioner:
        image: "raspbernetes/csi-external-provisioner:2.0.0"
      registrar:
        image: "raspbernetes/csi-node-driver-registrar:2.0.1"
      resizer:
        image: "raspbernetes/csi-external-resizer:1.0.0"
      snapshotter:
        image: "raspbernetes/csi-external-snapshotter:3.0.0"
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
