
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: velero
  chart:
    repository: https://vmware-tanzu.github.io/helm-charts
    name: velero
    version: 2.12.13
  valuesFrom:
    - secretKeyRef:
        name: velero-helm-values
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://minio.default.svc:9000
          publicUrl: https://minio.starbs.net
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 6h
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 2000Mi
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: "120h"
