---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  annotations: null
  cephVersion:
    allowUnsupported: false
    image: "ceph/ceph:v15.2.5"
  cleanupPolicy:
    allowUninstallWithVolumes: false
    confirmation: ""
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    disable: false
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    manageMachineDisruptionBudgets: false
    managePodBudgets: false
    osdMaintenanceTimeout: 30
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
  labels: null
  mgr:
    modules:
      - enabled: true
        name: pg_autoscaler
  mon:
    allowMultiplePerNode: false
    count: 2
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network: null
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    mon:
      limits:
        memory: 1024Mi
      requests:
        cpu: 35m
        memory: 800Mi
    osd:
      limits:
        memory: 4096Mi
      requests:
        cpu: 35m
        memory: 2048Mi
  skipUpgradeChecks: false
  storage:
    config:
      osdsPerDevice: "1"
    useAllDevices: true
    useAllNodes: true
