---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-helm-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBreeSk2BJRTU5OZ+eu1kO6Blq1sgqr+nLyWsjMToVduT3NMEHC5Yi8uEPXn+6f8sRIrtoXS8Ve3QDzr7G2lZ2Puv2MnReiTh6/xDUwG2XjfQ5gadLSpt1YBgD5TpGTutWQYCpJK9QzHctMC8P/djm+cCt6mnMd7cFqf/wqgEpeffTwbgambBAIjV96ho1gudPOiioIw5EeYC7okRqjOBseZyMLLNU2INF1MIHouepZzILxaFg5wTywdSFMckiHvAp1vkOHiwRYsetctrizIqk6BAk0jA23+SBlsWCB/gMNRDicw9JRu9/lZDYoyWatRSa1PoINljvTZnH77pCnRzLb6lQiZv/hpT+Zec0IwNZl5bFXUt77Dx6BRIyd4FyIEKD4Xbr7He9IZHtgEipy2kGqwDNiGJOFMKETj+sj9lxpu+oYXqYGg5jc5b5ON0tWFmGO7TEnVX8fdawX/oVDRzTyy5gVat84GKxfXzQmQ15WAq6CYDmmi/DE/skUGwocK9vjNOn971jXWdu+DcvXEjDYdoMRibuV+MuJeyco9Oc9dHzxAOijk5UPXraJvYjNNMU8+A6JqJSRE+tgHLvpUAkkjzqCe6d5lEvvNrXpr6i9V1o7xI8MPcfEX8rR1SP2HhYI+/nAjrcLT7DA1gD/T1JFsiHoGRRXZiew+f/e/EWzprQOHpxZGkCf7kkLGgGbMtMcKG43kM2lHAS+3Vj4sU4Brq/i4uuGRNyS1f9ykevDmP52zT4IK9EepKCGTyDIx29aH048TOZxQHuSJEIYPlZyXLKMLe4Hf3zXh6B0d0vMNNsqR3Fd9TpCopaldK7UnIHlUi4E3WIjARHMU4496DqYh74=
  template:
    metadata:
      creationTimestamp: null
      name: thanos-helm-values
      namespace: monitoring
    type: Opaque
