---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  chart:
    name: reloader
    repository: "https://stakater.github.io/stakater-charts"
    version: v0.0.69
  releaseName: reloader
