---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rook-direct-mount
  name: rook-direct-mount
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-direct-mount
  template:
    metadata:
      labels:
        app: rook-direct-mount
    spec:
      containers:
        - args:
            - "-g"
            - "--"
            - /usr/local/bin/toolbox.sh
          command:
            - /tini
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: ceph-username
                  name: rook-ceph-mon
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  key: ceph-secret
                  name: rook-ceph-mon
          image: "rook/ceph:master"
          imagePullPolicy: IfNotPresent
          name: rook-direct-mount
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev
              name: dev
            - mountPath: /sys/bus
              name: sysbus
            - mountPath: /lib/modules
              name: libmodules
            - mountPath: /etc/rook
              name: mon-endpoint-volume
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - hostPath:
            path: /dev
          name: dev
        - hostPath:
            path: /sys/bus
          name: sysbus
        - hostPath:
            path: /lib/modules
          name: libmodules
        - configMap:
            items:
              - key: data
                path: mon-endpoints
            name: rook-ceph-mon-endpoints
          name: mon-endpoint-volume
