---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: uptimerobot-prometheus
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: uptimerobot-prometheus
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: uptimerobot-prometheus
    version: 2.0.1
  valuesFrom:
    - secretKeyRef:
        name: uptimerobot-prometheus-helm-values
  values:
    image:
      repository: billimek/prometheus-uptimerobot-exporter
      tag: 0.0.1
    serviceMonitor:
      enabled: true
