---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: rook
  name: csi-metrics
  namespace: rook-ceph
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: csi-http-metrics
    - interval: 5s
      path: /metrics
      port: csi-grpc-metrics
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: csi-metrics
