---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    email: hello@chipwolf.uk
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - dns01:
          route53:
            accessKeyID: AKIAXSZNSZEEFRDIAZKB
            region: us-east-1
            secretAccessKeySecretRef:
              key: aws-secret-access-key
              name: route53-credentials
        selector: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: hello@chipwolf.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - dns01:
          route53:
            accessKeyID: AKIAXSZNSZEEFRDIAZKB
            region: us-east-1
            secretAccessKeySecretRef:
              key: aws-secret-access-key
              name: route53-credentials
        selector: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: cert-manager
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - starbs.net
    - "*.starbs.net"
