---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grocy
  namespace: default
spec:
  chart:
    name: grocy
    repository: "https://k8s-at-home.com/charts/"
    version: 2.0.0
  releaseName: grocy
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      hosts:
        - grocy.starbs.net
      tls:
        - hosts:
            - grocy.starbs.net
    persistence:
      config:
        skipuninstall: true
        storageClass: local-path
    timezone: Europe/London
    tolerations:
      - key: arm
        operator: Exists
