---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/ignore: "false"
  name: botkube
  namespace: monitoring
spec:
  chart:
    name: botkube
    repository: "https://infracloudio.github.io/charts"
    version: v0.11.0
  releaseName: botkube
  rollback:
    enable: true
  values:
    config:
      resources:
        - events:
            - create
            - delete
          name: pod
          namespaces:
            ignore:
              - kube-system
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: service
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - update
            - delete
            - error
          name: deployment
          namespaces:
            ignore:
              - null
            include:
              - all
          updateSetting:
            fields:
              - "spec.template.spec.containers[*].image"
            includeDiff: true
        - events:
            - create
            - update
            - delete
            - error
          name: statefulset
          namespaces:
            ignore:
              - null
            include:
              - all
          updateSetting:
            fields:
              - "spec.template.spec.containers[*].image"
            includeDiff: true
        - events:
            - create
            - delete
            - error
          name: ingress
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: node
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: namespace
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: persistentvolume
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: persistentvolumeclaim
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: secret
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - delete
            - error
          name: configmap
          namespaces:
            include:
              - all
        - events:
            - create
            - delete
            - error
            - update
          name: daemonset
          namespaces:
            ignore:
              - null
            include:
              - all
          updateSetting:
            fields:
              - "spec.template.spec.containers[*].image"
            includeDiff: true
        - events:
            - create
            - update
            - delete
            - error
          name: job
          namespaces:
            ignore:
              - kube-system
            include:
              - all
          updateSetting:
            fields:
              - "spec.template.spec.containers[*].image"
              - "status.conditions[*].type"
            includeDiff: true
        - events:
            - create
            - delete
            - error
          name: role
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: rolebinding
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: clusterrole
          namespaces:
            ignore:
              - null
            include:
              - all
        - events:
            - create
            - delete
            - error
          name: clusterrolebinding
          namespaces:
            ignore:
              - null
            include:
              - all
      settings:
        clustername: k8s
    serviceMonitor:
      enabled: true
  valuesFrom:
    - secretKeyRef:
        name: botkube-helm-values
