---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: botkube-helm-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: >-
      AgA3j/8MnEdstuiZ0McaY8kvJ/+t2UhumvUloDVXTJlEbHob/FKhVa90Ee9lMusFnu3RxIE7oRSs85QsXX3iKQIixkjdzI2DCtSLuketags5kXRvFl4DUsrTbZ2IcpANGjltdlYBax8C1SUpOd7AJDqKhNeD1HUEBMK+G8tyPVuZAcxG0yqHNR1Hh8+w91oBca2gjeyrw/NEBtc1DNe7ILa1hwdre2BjKaHl74n+fJXkpz6A9yv1rq2NhdJInARnpoNgOu3Q6GJcHKmcv8w5PNlLi2nYta7GDguqxNp1o/e8hTVbse/oEr0D25gCdIreVX6WapyRAHyyQT4ofIRcuQT7fi1u2XT32W8u7tXcGANKr+2+NmtKJsLFdsfcRh/084TI30LLUPRMoq8g8vp3y8Q9Z9tutiuEJP2cKLYY+1fPgQrM1hUGBA7xUYTz1A1RJXOj/iqhKexR7PMZYdLYjrouyMRbtYzJWgKRbyTa/zbnEKuNyaF6Q44I2c595Q/mXCN0yUidfm9sybbDopGYhBVxMpNmj9RYC7hjSt7pqjzuC6BtPjyQL14GLSW0TUGDqyHK+jUyWiNwrjiP9DfEskVk3MRaduY2tE88a0iNBcNZsTDNzbJeXU5Li5b+4ZZm2nc4uOEbPE7C+wmDkvpl0Te+cRJ/GzLphBTvVybv1AEbQWeNWV5XSafPJaoxuCW9HaLQN0oVLn4QdkEhdhbvkYrM8uNif7Ze9RtHi1A5zcw4HboqNTy28EeVluc505crmUl0kpH69wO/eSgyYW5vpWWe8RzWgDLfPlY9mWv0WinMQmO2Godo4sl3DDK+11TKtWjEpebShWp98ersdgwsXxV+a1YI/0bdivULLu2X3PKxv7Op58GIGR1Z97EoTB1HFajg6M2Pi3x7zOxf+XKmcDEnayln
  template:
    metadata:
      name: botkube-helm-values
      namespace: monitoring
    type: Opaque
