---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: descheduler
  name: descheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: descheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: descheduler
    spec:
      containers:
        - args:
            - "--policy-config-file"
            - /policy-dir/policy.yaml
            - "--evict-local-storage-pods"
            - ""
            - "--v"
            - "3"
            - "--descheduling-interval"
            - 2m
          command:
            - /bin/descheduler
          image: "us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.18.0"
          name: descheduler
          volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
      priorityClassName: system-cluster-critical
      serviceAccountName: descheduler-sa
      volumes:
        - configMap:
            name: descheduler-policy-configmap
          name: policy-volume
