---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 5.0.0
  valuesFrom:
    - secretKeyRef:
        name: radarr-helm-values
  values:
    image:
      repository: linuxserver/radarr
      tag: 3.0.0.3544-ls21
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 3Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
