---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 5.0.0
  values:
    image:
      repository: linuxserver/radarr
      tag: 3.0.0.3544-ls21
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts: [radarr.starbs.net]
      tls:
      - hosts:
        - radarr.starbs.net
    timezone: "Europe/London"
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        size: 2Gi
      media:
        enabled: true
        existingClaim: data
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
