---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/ignore: "false"
    fluxcd.io/tag.chart-image: "glob:RELEASE.*"
  name: minio
  namespace: default
spec:
  chart:
    name: minio
    repository: "https://helm.min.io/"
    version: 7.1.2
  helmVersion: v3
  releaseName: minio
  values:
    helmKubectlJqImage:
      repository: drnic/kubectl
      tag: 1.16
    image:
      repository: jessestuart/minio
      tag: RELEASE.2020-08-08T04-50-06Z
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      hosts:
        - minio.starbs.net
      tls:
        - hosts:
            - minio.starbs.net
    mcImage:
      repository: jessestuart/mc
      tag: RELEASE.2020-08-08T02-33-58Z
    metrics:
      serviceMonitor:
        enabled: true
    nasgateway:
      enabled: true
      replicas: 1
    persistence:
      size: 15Gi
      storageClass: local-path
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 25m
        memory: 350Mi
    securityContext:
      enabled: false
    tolerations:
      - key: "arm"
        operator: "Exists"
  valuesFrom:
    - secretKeyRef:
        name: minio-helm-values
