---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcloud
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluxcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
        - env:
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  key: slack_url
                  name: fluxcloud
            - name: SLACK_CHANNEL
              value: "#notifications"
            - name: SLACK_USERNAME
              value: Flux Deployer
            - name: SLACK_ICON_EMOJI
              value: ":heart:"
            - name: GITHUB_URL
              value: "https://github.com/chipwolf/k8s-gitops/"
            - name: LISTEN_ADDRESS
              value: ":3032"
          image: "justinbarrick/fluxcloud:v0.3.8"
          imagePullPolicy: IfNotPresent
          name: fluxcloud
          ports:
            - containerPort: 3032
      securityContext:
        runAsUser: 999
