---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: acme-crt
  namespace: kube-system
spec:
  dnsNames:
    - starbs.net
    - "*.starbs.net"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: acme-crt-secret
