---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: hello@chipwolf.uk
    privateKeySecretRef:
      name: letsencrypt-prod
    server: "https://acme-v02.api.letsencrypt.org/directory"
    solvers:
      - dns01:
          route53:
            accessKeyID: AKIAXSZNSZEEBXI7LHAG
            region: us-east-1
            secretAccessKeySecretRef:
              key: aws-secret-access-key
              name: route53-credentials
        selector: {}
