---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: "semver:~v1."
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    name: cert-manager
    repository: "https://charts.jetstack.io/"
    version: v1.0.3
  releaseName: cert-manager
  rollback:
    enable: false
  values:
    cainjector:
      replicaCount: 1
      tolerations:
        - key: "arm"
          operator: "Exists"
    extraArgs:
      - "--dns01-recursive-nameservers=9.9.9.9:53"
      - "--dns01-recursive-nameservers-only"
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring
    tolerations:
      - key: "arm"
        operator: "Exists"
    webhook:
      enabled: true
      tolerations:
        - key: "arm"
          operator: "Exists"
