---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    aws-secret-access-key: >-
      AgBiEGaqZfSOo7o+x2/Oknr1RaUXOaH+YK0hDY5i+yMTcropWpFSCf+br6jUEa51xsLMthLTjm4b9x6hv31S/BM6nzYEuEnmwRERjr4ijvCAJs88f5NvJbhmU5DeUlCQx+GEJgHelEnZE1VwniJnbjnkfzHRnM9nXtBCwwLpGjalylB8PlBXLRpAGp16+euT1dwGDSyw038Afa1bI39EUY0TS7frKlw7FD7GhXqhDlgOYoxoDStEdDraKrIouegqRI44dmA/7DspuuFo50eDcG4J8lcvEmngips4Da1khs+37jZ5LtIJ2h4NvnjnhJT3Tyzj6uMPaj72sZ+esBADHKaT17GU2bFFxNbFSpljgQP7EuK6rCtnJoH4U0R/5mCBszA+3U20q6eGUqP0oz7J8Xh+4evb3h5aSxYzCbkqQd30ZTKh7NBqN5PDos8cUPU8m0bYDRGJx11eAIz1c4muOrrDYT9s3rlQdf3LG78+iJZtjR5adgTxP8SZBmWGUl/l8qskz2lrhBmbww2BL0zoqamrGOV3xwonADUKfHl/2vKknuF2i7+ILOToTNAlrS9DC2EMeB3/6u1CVwhzqJ2FWXUP4Nkn8WqHP8ynfLC+g5ph/vLHlwAd127BU/Njt7tMtw5Hj6lYgS0y4npfk5+haw/VPQORUbWrHo/kuvZx8uz8nBVdQFq8iSEsgniNj3AxxNRhNOJ0FMbIU031TRE76dUllyhVgYryqLlpKUUwocPkxFEvpTReKrbv
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
    type: Opaque
