---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    aws-secret-access-key: AgAGLJAkN5KzzP3LeFLi4cLTlKPPJTaUwp5j2MG2rspIiCvGirlJdU1JPa2A1VOdf5ywafm11APOG2lltRM8DMxAj+jtAk8hr4nI/tS0NdBh0wXVTR09hEaG6THGJZsRR49awLU5GfIC1YxdygvUXbTUKPWHxcsRuI6GPW03P7p0I/XcpvnqYk2U6/6I+Tzx2dSyyEpOnIgqo1amp3aTB8LpWMvwHF8WL79T5Lg+LPLfB2AX/3EGvEYr6xBpooPqr22pRyh8IvzUzbJMpn+8jukWmyvbTKnFBFs7p4R5da6uCyZKwzpRKTBmkLyahfcctZ+HPpxWuO3eFaQg5Hx/JkbkRWK1BLVK4XSKMpHrb4Xvi3USh65yWSIiFiNELqkzsJ/1TcQyOIb6fAEwsGMqccEecpdb/NIl6mfbIyTvmksLyhCUtZg5+vtixrn8VQdXSemNhy7kplRO6v950DSMOzJBMz3BEoruZEFlgcrArYJnAFM5gA2h3hgVcPEf4sOGoquyRMs4mq1lb5bTyVVWo6wujid8uWxKZd0NCXL5NalYDAPun/rX6j7DOUi53FUkNnUvJ0mNE7yKw1bYPdTWSyWnBNwkrzWIvjVQYaB5iSwqsU1EUnwyH7/X/xebIuNtlHAoyqU5y8KZtGZoaouM51thI1oqZ4G/IHGGtj/0MJDitHg1uZ+QknSvDTzpwa9PYd/9qIkLZBGuVW6bDUdx0L6MKLrbejAvgzQjMgI3Tl8=
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
