---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: 'regex:^(1\.[0-9]+\.[0-9]+-12-minimal)$'
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "false"
  name: node-red
  namespace: default
spec:
  chart:
    name: node-red
    repository: "https://k8s-at-home.com/charts/"
    version: 3.1.0
  helmVersion: v3
  releaseName: node-red
  rollback:
    enable: true
  values:
    enableProjects: true
    flows: flows.json
    image:
      repository: nodered/node-red
      tag: 1.2.6-12-minimal
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      hosts:
      - node-red.starbs.net
      tls:
      - hosts:
        - node-red.starbs.net
    persistence:
      enabled: true
      storageClass: local-path
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 25m
        memory: 350Mi
    timezone: Europe/London
    tolerations:
    - key: arm
      operator: Exists
