---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(1\.[0-9]+\.[0-9]+-12-minimal)$
spec:
  releaseName: node-red
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: node-red
    version: 3.1.0
  values:
    image:
      repository: nodered/node-red
      tag: 1.2.3-12-minimal
    persistence:
      enabled: true
      storageClass: "local-path"
    flows: "flows.json"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts: [node-red.starbs.net]
      tls:
      - hosts:
        - node-red.starbs.net
    timezone: "Europe/London"
    enableProjects: true
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
