---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0.
spec:
  releaseName: ingress-nginx
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.4.1
  values:
    controller:
      replicaCount: 2
      config:
        custom-http-errors: 404,401,403,500,503
        # global-auth-url: "http://oauth2-proxy.kube-system.svc.cluster.local/oauth2/auth"
        # global-auth-signin: "https://auth.$server_name/oauth2/start"
      use-forwarded-headers: "true"
      service:
        loadBalancerIP: 172.16.1.119
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "kube-system/acme-crt-secret"
      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 600Mi
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi
