---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.3
  valuesFrom:
  - secretKeyRef:
      name: plex-helm-values
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.20.4.3517-ab5e1197c
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts: [plex.starbs.net]
      tls:
      - hosts:
        - plex.starbs.net
    timezone: "Europe/London"
    plexUid: 1001
    plexGid: 1001
    serviceTCP:
      type: LoadBalancer
      loadBalancerIP: 172.16.1.115
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: plex
    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: 172.16.1.115
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: plex
    persistence:
      transcode:
        enabled: true
        claimName: data
        subPath: plex
      data:
        enabled: true
        claimName: data
      config:
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 2Gi
    resources:
      limits:
        gpu.intel.com/i915: 1
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
